export const DOUBAO_RESEARCH_STABLE_MODEL =
  process.env.DOUBAO_RESEARCH_MODEL?.trim() || "doubao-seed-2-0-lite-260215"

export const RESEARCH_STAGE_TIMEOUT_SECONDS = 150
export const COMPETITOR_STAGE_TIMEOUT_SECONDS = 150

export const RESEARCH_EVIDENCE_CACHE_SECONDS = 2 * 60 * 60
